scrape/urls.py
from django.conf.urls import url

from . import views

app_name = 'scrape'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^scrape/$', views.post, name='post'),
    url(r'^(?P<post_body>.[ \w-]+)/results/$', views.scraped, name='scraped')
]

scraper/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^scraper/', include('scrape.urls'))
]

scrape/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

scrape/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from pymongo import MongoClient
from bs4 import BeautifulSoup
import requests

# client = MongoClient('mongodb://localhost::27017/')
# db = client.scraper
# collection = db.posts


def find(val):
    search = requests.get("https://en.wikipedia.org/wiki/" + val)
    c = search.content
    soup = BeautifulSoup(c, 'html.parser')
    return soup.prettify()


def index(request):
    return render(request, 'scrape/index.html')


def scraped(request, post_body):
    context = {'body': post_body, 'res': find(post_body)}
    return render(request, 'scrape/results.html', context)


def post(request):
    post_body = request.POST['body']
    return HttpResponseRedirect(reverse('scrape:scraped', args=(post_body,)))

scrape/templates/scrape/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Web Scraper</title>
</head>
<body>
<h1>Scrape the web</h1>
<form action="{% url 'scrape:post' %}" method="post">
{% csrf_token %}
    <input type="text" name="body">
    <input type="submit" value="Search">
</form>
</body>
</html>

scrape/templates/scrape/results.html
<h1>You searched for: {{ body }}</h1>

<pre><code>{{ res }}</code></pre>